# refer to Mtb_modules_notebook.Rmd

# Counts generated using baerhunter feature_count function
# used combined feature gff generated by running bh on these same datasets

# normalisation and plots from YenYi's MSc project
# https://github.com/yenyi1995/Large-Scale-Computational-Analysis-of-Coding-and-Non-coding-Element-Expression-in-Mtb/blob/master/MSci%20Research%20Project%20Code.R

#Quantification, normalisation and clustering analysis
#The following is an R script used to perform normalisation and hierarchical 
#clustering analysis of count data 

install.packages("dendextend")
library(dendextend)
install.packages("viridis")
library(viridis)
library(colorspace)
library(RColorBrewer)
BiocManager::install("sva")
library(sva)
BiocManager::install("limma")
library(limma)
BiocManager::install("WGCNA")
library(WGCNA)
library(dplyr)
library(ggplot2)

# dataset name for index (my order is different from Yenyi--change to match my countsdata)
View(sample_df)
dataset<-c(rep("PRJEB65014_3/E-MTAB-6011", 3), 
           rep("PRJNA327080/GSE83814", 15),
           rep("PRJNA278760/GSE67035", 22),
           rep("PRJNA390669/GSE100097", 12))
#boxplot for original data 
dds.untransformed <- assay(dds)
colnames(dds.untransformed)<-colnames(dds)
par(cex.axis=0.5) 
par(mar=c(4,2,1,1))
colors = c(rep("#440154FF",3),rep("#31688EFF",15),rep("#FDE725FF",22),rep("#35B779FF",12))
plot.new()
original.boxplot <- boxplot(dds.untransformed, 
                            PchCex =0.01,
                            axes=TRUE,
                            las=2,
                            col=colors, 
                            ylim = c(0,4500),
                            outline =TRUE,
                            outcex=0.35)

legend("topleft", 
       legend=c("E-MTAB-6011", "GEO:GSE83814", "GEO:GSE67035", "GEO:GSE100097"),          
       col = c("#440154FF","#31688EFF","#FDE725FF","#35B779FF"), 
       fill= c("#440154FF","#31688EFF","#FDE725FF","#35B779FF"),
       cex = 0.75, 
       )


#boxplot for vst data 
dds.vsd <- assay(vsd)
colnames(dds.vsd)<-colnames(dds)
par(cex.axis=0.5)
par(mar=c(4,2,1,1))
colors = c(rep("#440154FF",3),rep("#31688EFF",15),rep("#FDE725FF",22),rep("#35B779FF",12))
vsd.dds.boxplot <- boxplot(dds.vsd,
                           PchCex =0.01,
                           axes=TRUE,
                           las=2,
                           col=colors,
                           outcex=0.35)
legend("topleft", 
       legend=c("E-MTAB-6011", "GEO:GSE83814", "GEO:GSE67035", "GEO:GSE100097"), 
       col=c("#440154FF","#31688EFF","#FDE725FF","#35B779FF"),
       fill=c("#440154FF","#31688EFF","#FDE725FF","#35B779FF"),
       cex=0.75)

#PCA plotting with DESeq2 in built function 
PCA.prelim <- plotPCA(vsd,intgroup="control.condition")

#generating PCA table 
PCA.data <- data.frame(row.names=colnames(countdata),
                       condition=factor(control.metadata$condition),
                       dataset=factor(control.metadata$study))
PCA.data.plot <- prcomp(t(dds.vsd))
df.vst <- as.data.frame(PCA.data.plot$x)
df.vst$group <- PCA.data$condition
df.vst$dataset <-PCA.data$dataset
summary(PCA.data.plot)

#establishing a custom viridis colour palette
toned_down_pal <- c("#FFBF00","#31688EFF","#35B779FF","#CA0020")

#PCA plot for VST transformed data 
custom <- ggplot(df.vst,aes(x=PC1,y=PC2,color=dataset,shape=group)) + scale_shape_manual(values = 0:16) + geom_point(size=3) + xlab("PC1 (42%)") + ylab("PC2 (32%)")
custom <- custom + scale_color_manual(values = toned_down_pal) + theme_bw()
custom

#dendrogram for VST transformed data


sizeGrWindow(12,9)
par(cex=0.6)
par(mar=c(5,6,2,0))


group <-as.factor(control.metadata$study) 
n_group <- length(unique(group)) 
cols <- toned_down_pal(n_group)
col_group <- cols[group] 
hc <- hclust(dist(t(dds.vsd)),method="average")
dend <- as.dendrogram(hc) 
col_group <- col_group[order.dendrogram(dend)] 
dend <- dend %>% 
set("labels_colors", col_group) %>% #change label colors to group
plot(main = "Dendrogram VST transformed")
legend("topright", 
       legend = unique(group), 
       fill = cols, 
       cex = 0.75, 
       pt.cex = 1)


#dendrogram for VST transformed data post-limma
sizeGrWindow(12,9)
par(cex=0.6)
par(mar=c(5,6,2,0))
group <-as.factor(control.metadata$study) 
n_group <- length(unique(group)) 
cols <- toned_down_pal 
col_group <- cols[group] 
hc.limma <- hclust(dist(datExpAdj),method="average")
dend.limma <- as.dendrogram(hc.limma)
col_group <- col_group[order.dendrogram(dend.limma)] 

dend.limma <- dend.limma %>% 
        set("labels_colors", col_group) %>% #change label colors to GROUP
        plot(main = "Dendrogram VST transformed post-Limma")
legend("topright", 
       legend = levels(group), 
       fill = cols, 
       cex = 0.75,
       pt.cex = 1)
